[tool.pytest.ini_options]
pythonpath = [
    ".",
    "src",
    "tests",
]
addopts = [
    "--cov=src",
    "--cov-report=term-missing",
    "--cov-report=html",
    "--cov-report=xml",
    "--cov-branch",
    # "--cov-fail-under=90",
    "--cov-context=test",
    # "--cache-clear",
]
testpaths = [
    "tests",
]
