name: Python CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov ruff coverage-badge

      - name: Run Ruff linter
        run: ruff check .

      - name: Run tests with coverage
        run: pytest --cov=.

      - name: Generate coverage badge
        run: |
          coverage-badge -o coverage.svg -f

      - name: Update README.md with CI status and coverage badge
        run: |
          CI_BADGE="![CI Status](https://github.com/${{ github.repository }}/actions/workflows/run_test.yml/badge.svg)"
          COVERAGE_BADGE="![Coverage](https://raw.githubusercontent.com/${{ github.repository }}/master/coverage.svg)"
          
          sed -i "/^# .*$/a \\
          $CI_BADGE\\
          $COVERAGE_BADGE" README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add coverage.svg README.md
          git commit -m "Update CI status and coverage badge" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
